# == 1. IMAGEN BASE ==
# Usamos el servidor web Nginx
FROM nginx:alpine

# == 2. COPIAR LA WEB ==
# Copiamos todos los archivos del frontend a la carpeta que usa Nginx por defecto
COPY . /usr/share/nginx/html

